manubot/metadata.py

Always set the URL for a DOI using the DOI.
Fixes https://travis-ci.org/greenelab/manubot/builds/262063044#L1509-L1520:
```
=================================== FAILURES ===================================
____________________ test_citation_to_citeproc_doi_datacite ____________________
def test_citation_to_citeproc_doi_datacite():
citation = 'doi:10.7287/peerj.preprints.3100v1'
citeproc = citation_to_citeproc(citation)
assert citeproc['id'] == '11cb5HXoY'
>       assert citeproc['URL'] == 'https://doi.org/10.7287/peerj.preprints.3100v1'
E       AssertionError: assert 'https://peer...rints/3100v1/' == 'https://doi.o...prints.3100v1'
E         - https://peerj.com/preprints/3100v1/
E         + https://doi.org/10.7287/peerj.preprints.3100v1
tests/test_citations.py:66: AssertionError
```

DOI citeproc URL: always overwrite URL

---

manubot/manubot.py

Related to https://codeyarns.com/2017/02/22/python-json-dump-misses-last-newline/
See also [source code](https://github.com/python/cpython/blob/4388b4257abf3b9c348cf4db8c6144dcc07f3e98/Lib/json/tool.py#L46) of `python -m json.tool`.

Newline at end of JSON files

---

manubot/manubot.py

Previousely, manual references were not getting used.

Fix manual references bug

---

manubot/manuscript.py
tests/test_manuscript.py

Prevents substrings of longer citation strings from shortcircuiting
the regex match and substitution.
Closes https://github.com/greenelab/manubot/issues/9

Fix lookahead in citation string regex

---

manubot/citations.py

Use "entry" for invalid types.
https://github.com/citation-style-language/schema/blob/4846e02f0a775a8272819204379a4f8d7f45c16c/csl-types.rnc#L5-L39
http://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html

Ensure CSL type is always valid

---

manubot/arxiv.py

See this [Deep Review build](https://travis-ci.org/greenelab/deep-review/builds/297004423#L1423) where several arXiv preprints have DOI info (published in journal):
```
arXiv article 1503.01919 published in"Algorithms for Computational Biology 9199 (2015) 68" at https://doi.org/10.1007/978-3-319-21233-3_6
arXiv article 1603.09195 published in"PLoS ONE 12(6): e0178751" at https://doi.org/10.1371/journal.pone.0178751
arXiv article 1607.00133 published in"None" at https://doi.org/10.1145/2976749.2978318
arXiv article 1609.02374 published in"None" at https://doi.org/10.1007/s11548-017-1567-8
arXiv article 1610.04181 published in"None" at https://doi.org/10.1093/bioinformatics/btx196
arXiv article 1702.05747 published in"None" at https://doi.org/10.1016/j.media.2017.07.005
```
Several have a …

Improve arXiv published DOI warning

---

manubot/manubot.py
tests/manuscripts/example/content/01.front-matter.md
tests/manuscripts/example/content/metadata.yaml
tests/test_citations.py
tests/test_manubot.py

Generate author affiliation numbering using Manubot. These are exposed as part of the template variables, so that manuscripts can use them. This will assist with alternative frontmatter styles, like the format desired by the Deep Review, see https://github.com/greenelab/deep-review/issues/700.
Todos:

Author affiliation numbering

---

manubot/metadata.py
manubot/pubmed.py
tests/manuscripts/example/content/02.body.md
tests/test_citations.py

This pull request migrates the previous `pmid` citations functionality (from NCBI Citation Exporter) to `pmcid`. This is more accurate because the NCBI Citation Exporter only works for records in PubMed Central. `pmid` citations are now supported that use the NCBI E-Utilities. `pubmed.py` enables parsing the XML returned by from E-Utilities into JSON CSL metadata.
Closes https://github.com/greenelab/manubot/issues/21
Refs https://github.com/ncbi/citation-exporter/issues/3

PubMed ID citation support

---

manubot/citations.py

No longer extract most email addresses as citations.
Closes https://github.com/greenelab/manubot/issues/25

Citation regex: negative lookahead for word chars

---

manubot/manubot.py

I noticed the following in `variables.json`:
```json
"date": "January  9, 2018",
```
There are two spaces since 9 gets a space prepended. Does not effect days > 9. See https://stackoverflow.com/questions/904928.
```python
>>> import datetime
>>> now = datetime.datetime(2018, 1, 9, 23, 8, 50, 558715)
>>> f'{now:%B %e, %Y}'  # Problem
'January  9, 2018'
>>> f'{now:%B %-e, %Y}'  # Fix (linux only)
'January 9, 2018'
>>> f'{now:%B} {now.day}, {now.year}'  # Fix (more general)
'January 9, 2018'
```

Remove extra space between month and day

---

manubot/manubot.py

These will be useful to construct links to GitHub Pages URLs, which are formatted like:
```
https://{repo_owner}.github.io/{repo_name}/
```

Variables: set ci_source.repo_owner / repo_name

---

manubot/cite/__init__.py
manubot/cite/citeproc.py

Reduces the chance of code failing due to missing these dependencies.

Do not import jsonref & jsonschema unless CSL pruning

---

.travis.yml
manubot/cite/cite_command.py
tests/cite-command-rendered/references-html.html
tests/cite-command-rendered/references-jats.xml
tests/cite-command-rendered/references-markdown.md
tests/cite-command-rendered/references-plain.txt
tests/test_citations.py

~~Work in progress.~~ Meant to partially fix extra newlines in markdown output from `manubot cite --render`.

For pandoc markdown format, use --wrap=none

---

manubot/cite/cite_command.py

Do not exit program when a citation_to_citeproc lookup fails. Instead set a nonzero exit code, but proceed with passing citaitons. Error messages are logged, full stacktrace is logged at INFO level.

Cite command error handling

---

manubot/cite/cite_command.py
manubot/cite/util.py
manubot/process/manuscript.py
manubot/process/util.py
tests/test_citations.py

Closes https://github.com/greenelab/manubot/issues/71

Validate citation identifiers conform to known identifier patterns

---

manubot/cite/cite_command.py
manubot/cite/citeproc.py
manubot/cite/pubmed.py
manubot/cite/util.py
tests/test_citations.py

NCBI Citaiton Exporter was taken offline without notice:
https://twitter.com/dhimmel/status/1061787168820092929

get_pmc_citeproc: switch to Literature Citation Exporter

---

.gitignore
manubot/cite/arxiv.py
manubot/cite/doi.py
manubot/cite/isbn.py
manubot/cite/pubmed.py
manubot/cite/url.py
manubot/util.py
setup.py

Adds new manubot contact email to user-agent, which can be helpful so resources can contact us regarding our API requests. Adds platform and python version info to user-agent so the upcoming translation-server can monitor usage.

Enhanced API calls: set User-Agent header & E-Utility rate limits

---

manubot/cite/isbn.py
manubot/cite/url.py
manubot/cite/zotero.py
tests/test_zotero.py

Use manubot's translation server to retrieve metadata for URLs and ISBNs. Switch URLs and ISBNs to use fallback methods if translation-server fails.
Closes #70.

Integration with the translate.manubot.org translation-server

---

manubot/cite/cite_command.py
manubot/cite/tests/test_cite_command.py
manubot/pandoc/util.py
setup.py

Move get_pandoc_info to manubot.pandoc.util.
Use packaging.version.parse to parse pandoc version string
This PR takes parts from https://github.com/manubot/manubot/pull/99, hoping to break that PR into more manageable chunks.
The `manubot.pandoc` module will be helpful for https://github.com/manubot/manubot/issues/100 / https://github.com/manubot/manubot/pull/99.

Create pandoc submodule

---

MANIFEST.in
manubot/cite/tests/test_zotero.py
setup.py

In https://github.com/manubot/manubot/pull/51, we could not get `package_data` in `setup.py` to work on Windows. We reported the issue in https://github.com/pypa/setuptools/issues/1459 and switched to using `MANIFEST.in`. The downside of MANIFEST is that it creates an extra file in the root directory of the repository for a rather obscure technical purpose.
In https://github.com/pypa/setuptools/issues/1459#issuecomment-493506713, @aschmied hypothesized `package_data` did not work for us because we passed a string rather than a list. This PR switches back to the `package_data` with the correct syntax.

setup.py: use package_data not MANIFEST to include data files

---

manubot/process/process_command.py

Closes https://github.com/manubot/manubot/issues/102
Make any missing parent directories for the `--output-directory` and `--cache-directory` arguments of `manubot process`.

process command: make parent directories

---

manubot/cite/tests/test_citeproc.py
manubot/pandoc/tests/test_bibliography.py

The change is needed to make test suite to run on non-latin OEM encoding on Windows.

test_remove_jsonschema_errors() forced to use utf-8

---

.gitignore
.travis.yml
ci/deploy-docs.sh
setup.py

Closes https://github.com/manubot/manubot/issues/117
After merge, docs should be regenerated for each commit and deployed to gh-pages. Uses https://github.com/timothycrosley/portray

Generate docs and deploy to gh-pages

---

manubot/cite/citekey.py
manubot/cite/citeproc.py
manubot/cite/csl_item.py
manubot/cite/tests/test_citeproc.py
manubot/cite/tests/test_csl_item.py
manubot/process/bibliography.py

Migrate additional functionality to the CSL_Item class. Specifically, csl_item_set_standard_id is now CSL_Item.starndardize_id. append_to_csl_item_note is now note_append_dict and note_append_text

Migrate csl_item_set_standard_id to CSL_Item class

---

.appveyor.yml
.travis.yml
conftest.py
setup.py

AppVeyor does not support Python 3.8 yet as per https://github.com/appveyor/ci/issues/3142.

Test on Python 3.8

---

manubot/process/tests/test_thumbnail.py
manubot/process/thumbnail.py
manubot/process/util.py
manubot/tests/test_thumbnail.py

Refs https://github.com/manubot/rootstock/issues/267
This commit adds a `thumbnail_url` field to `output/variables.json`. The thumbnail can be specified by a repo-relative path, an existing URL, or automatically detected if `thumbnail.png` exists.
git_repository_root is derived from _git_project_root in https://github.com/pdoc3/pdoc/commit/b47e916d78821dd9918b83f4a23b859b9cc473c5.

Support metadata.thumbnail / variables.thumbnail_url

---

manubot/process/thumbnail.py
manubot/process/util.py
manubot/util.py

is_http_url functionality was being performed in two places with different implementations.

Move is_http_url to manubot.util

---

manubot/process/header-includes-template.html
manubot/process/metadata.py
setup.py

Previously pandoc was producing the following from our `header-includes` that was wrapped in a code block:
```html
<code>html {=html} &lt;!-- Manubot generated metadata rendered from header-includes-template.md. Suggest improvements at https://github.com/manubot/manubot/blob/master/manubot/process/header-includes-template.md --&gt; &lt;meta name="dc.format" content="text/html" /&gt; &lt;meta name="dc.title" content="Manuscript Title" /&gt; &lt;meta name="citation_title" content="Manuscript Title" /&gt; &lt;meta property="og:title" content="Manuscript Title" /&gt; &lt;meta property="twitter:title" content="Manuscript Title" /&gt; &lt;meta name="dc.date" content="2019-11-19" /&gt; &lt;meta name="citation_publication_date" content="2019-11-19" /&gt; &lt;meta name="dc.language" …
```

header-includes-template.html: don't encapsulate in code block

---

manubot/cite/citekey.py
manubot/cite/tests/test_citekey.py
manubot/cite/tests/test_url.py

closes https://github.com/manubot/manubot/issues/61
currently, `url_to_citekey` is not used by Manubot, but is a convenience function for users of the package.
todo:

url_to_citekey: convert from URL to citekey

---

manubot/process/tests/manuscripts/example/content/metadata.yaml
manubot/process/util.py

'authors' as a key is more consistent with other YAML metadata
frontmatters in the space.

process: YAML metadata use 'authors' not 'author_info'

---

manubot/process/util.py

I've resumed work on #99, which needs to access some functions from manubot.cite.util in a more general purpose way (without requiring argparse args for example).
These commits are currently in that PR, but may make sense to merge first, since #99 could take a while.

process.util: improve modularity of get_citekeys_df and generate_csl_items

---

.flake8
.travis.yml
README.md
manubot/cite/arxiv.py
manubot/cite/wikidata.py
manubot/tests/test_imports.py
setup.py

black alone is insufficient to catch errors like undefined variables and unused imports. flake8 does this well, but needs some small configuration as to not fight black.
flake8 does not yet support configuration using pyproject.toml.
Use black configuration as template:
https://github.com/psf/black/blob/1ab87a3f67bc80a2e59be2692f2e2f25dd143af7/.flake8
Changed max complexity since refactor complex functions is outside
the scope of this change.
Enable flake8 checking in CI.
setup.py: rename test extra requirements to dev.

Configure & enforce flake8 linting

---

manubot/cite/arxiv.py
manubot/cite/citekey.py
manubot/cite/tests/test_arxiv.py
manubot/cite/tests/test_citekey_api.py

OAI endpoint adds license and author first/last, but cannot do versioned arxiv links

arxiv metadata: use OAI endpoint for better metadata

---

README.md
manubot/process/bibliography.py
manubot/util.py
setup.py

Closes #204 
When reading a .yaml file fails, provide yamllint to stderr if possible.

yamllint failing YAML files

---

manubot/cite/doi.py
manubot/cite/tests/test_doi.py

Refs https://github.com/manubot/manubot/issues/158
DataCite's Content Negotiation returns valid CSL JSON even for Crossref DOIs.
https://github.com/crosscite/content-negotiation/issues/92
https://support.datacite.org/docs/datacite-content-resolver

DOI metadata: use DataCite Content Negotiation

---

README.md
manubot/cite/tests/test_unpaywall.py
manubot/command.py
manubot/process/manuscript.py
manubot/process/tests/test_manuscript.py
manubot/process/tests/test_process_command.py
manubot/process/util.py

Remove support for citation processing in manubot process, in favor of using the pandoc-manubot-cite filter for all processing.
`pandoc-manubot-cite` does have a stricter syntax for what characters are allowed in citekeys. So we'll have to update the rootstock USAGE when upgrading manubot in Roostock.
My plan is to start more aggressively removing deprecated features like this to make the transition to `manubot/template` easier.

manubot process: require --skip-citations

---

manubot/process/ci.py

If the environment variable CI=true and no supported provider
detected, then we want to warn.

get_continuous_integration_parameters: fix bug

---

manubot/process/tests/manuscripts/example/content/01.front-matter.md
manubot/process/tests/manuscripts/example/content/metadata.yaml
manubot/process/util.py

refs https://github.com/manubot/rootstock/issues/329
In local output, got the following for legacy affiliations.
```
/home/dhimmel/Documents/repos/manubot/manubot/process/util.py:150: DeprecationWarning: Expected list for Daniel S. Himmelstein's affiliations. Assuming multiple affiliations are `; ` separated. Please switch affiliations to a list.
category=DeprecationWarning,
```

metadata: convert author.funders to list

---

.github/workflows/test.yml
manubot/cite/tests/test_curie.py

fixup ea11343033a5d3a357eb325cfc8a5574ac00459f
the python-version parameter was accidentally deleted from the
Install Python step. Therefore, actions was only testing on the
default Python.

actions: restore python-version functionality

---

manubot/cite/citeproc.py
manubot/cite/isbn.py
manubot/cite/pubmed.py
manubot/process/manuscript.py
setup.py

The https://github.com/citation-style-language/schema repo has had some nice maintenance recently and the schema has been updated to `draft-07`.

Update CSL JSON Schema & housekeeping

---

manubot/cite/citeproc.py
manubot/util.py

In 1c3c74b, we upgraded the CSL JSON Schema at
https://github.com/dhimmel/csl-schema/raw/manubot/csl-data.json
and updated get_jsonschema_csl_validator in a way that requires
the new schema.
However, this caused rootstock repo pull request to fail after
upgrading manubot because the outdated csl-data.json schema was cached.
https://github.com/manubot/rootstock/pull/342#issuecomment-633309646
This should work because we set include_get_headers=True in
requests_cache.install_cache.
Another options would be
with requests_cache.disabled():
requests.get(url)
https://requests-cache.readthedocs.io/en/latest/api.html#requests_cache.core.disabled

one-time reset of the CSL JSON Schema requests cache

---

.appveyor.yml
.github/workflows/test.yml
.travis.yml
conftest.py
manubot/cite/tests/test_cite_command.py
manubot/pandoc/tests/test_cite_filter.py
manubot/process/tests/test_ci.py
manubot/process/tests/test_process_command.py
manubot/webpage/tests/test_webpage_command.py

now that GitHub Actions is comprehensively testing and deploying,
use travis and appveyor only for tests where they provide unique
coverage.
Should help avoid intermittent failures from upstream resources
and avoid performing extra compute for little benefit.

reduce travis and appveyor CI duties

---

README.md
manubot/cite/cite_command.py
manubot/command.py
manubot/pandoc/bibliography.py
manubot/process/bibliography.py
manubot/util.py

- fixup 47b03e0c202e6a0561e6548ba08a4ad790f56eee reenable --allow-invalid-csl-data
- --csl or --format implies --render
- reorder args so most common ones first
- switch URL for default CSL Style to https://citation-style.manubot.org/
- enable `--bibliography` as URL for `.json` or `.yaml` files. Pandoc does not support URL for `--bibliography` yet

cite command enhancements

---

manubot/cite/arxiv.py

`{arxiv_id}` and `{response_arxiv_id}` were not being replaced as the f-string identifier was missing.

Fix oai logging

---

manubot/cite/citekey.py
manubot/cite/csl_item.py
manubot/cite/handlers.py
manubot/cite/pubmed.py
manubot/cite/tests/test_citekey.py
manubot/cite/tests/test_citekey_api.py
manubot/util.py

I'd like to begin more comprehensively typing this package, with the eventual goal of running a static type checker like mypy. In the meantime, these types help as documentation.

Add typing to manubot.cite.pubmed

---

manubot/cite/csl_item.py
manubot/cite/tests/test_csl_item.py

refs https://github.com/manubot/manubot/issues/258
Enables using the bibliography output as the bibliography input for the next run of pandoc-manubot-cite, repeating this process many times as a form of caching and reuse of retrieved reference metadata. Avoids accumulated duplicate note text.

CSL_Item: do not append duplicate lines to a note

---

setup.cfg

We included the following to exclude tests from our distributions:
https://github.com/manubot/manubot/blob/0c2e5b28809acd7c9ca76152146ddc24345d0781/setup.cfg#L71-L73
But that doesn't actually work. It only works to exclude a top-level `tests` directory from being detected by `find_packages`.

fix exclusion of tests in wheel distribution

---

manubot/cite/arxiv.py
manubot/cite/unpaywall.py
manubot/cite/url.py

closes https://github.com/manubot/manubot/issues/278
use response.raise_for_status() to raise an exception with an error message like:
> 503 Server Error: Retry after specified interval for url: https://export.arxiv.org/oai2?verb=GetRecord&metadataPrefix=arXiv&identifier=oai%3AarXiv.org%3A1607.00653
This message contains the bad status code and the URL.

cite requests: better error messages

---

README.md
manubot/command.py
manubot/process/metadata.py
manubot/process/util.py

closes https://github.com/manubot/manubot/issues/290
Addresses https://github.com/manubot/manubot/issues/290 and related issues by adding the `--skip-remote` command-line flag to `manubot process` that will skip over fetching the rootstock commit ID and therefore not adding the rootstock git remote to the local git repository.
This makes life a bit easier for those using manubot in a non-standard way, such as outside the rootstock repository.
Implementation is up for discussion but I've tested this one and it works locally.

Add command-line argument to skip adding the rootstock git remote

---

manubot/cite/doi.py
manubot/cite/tests/test_doi.py

refs https://github.com/manubot/manubot/issues/309
The DataCite content negotiation (via `https://data.crosscite.org`) tends to produce better metadata but fails often. Adds fallback to CrossCite content negotiation (via `https://doi.org`).

get_doi_csl_item: try crosscite if datacite fails

---

manubot/cite/doi.py

fixes https://github.com/manubot/manubot/pull/310/files#r780685302
partial does not set `__name__` causing downstream error message to
raise an exception.

get_doi_csl_item_negotiation: do not use partial

---

manubot/process/metadata.py
manubot/process/util.py

refs https://github.com/manubot/manubot/issues/315
Enables setting the following in metadata.yaml:
```yaml
manubot-randomize-author-order: true
```

Support metadata.manubot-randomize-author-order

---

manubot/cite/doi.py
manubot/cite/tests/test_doi.py
manubot/pandoc/tests/test_cite_filter.py
manubot/pandoc/tests/test_cite_filter/input.md
manubot/pandoc/tests/test_cite_filter/output.txt
manubot/webpage/tests/test_webpage_command.py

refs https://github.com/manubot/manubot/issues/309
refs https://github.com/crosscite/content-negotiation/issues/104
DataCite has stopped returning content negotiation results for Crossref DOIs. This change might be temporary or permanent, awaiting further deliberation.

Use DOI.org content negotiation only, fallback to URL metadata for DOIs

---

manubot/cite/isbn.py

I've reduced the scope of changes on #338 [as requested](https://github.com/manubot/manubot/pull/338#issuecomment-1183912661):
> So in the interest of quickly merging, can we reduce this PR (or a new one) to just address the requests that are known to timeout?
>
> _Originally posted by @dhimmel in https://github.com/manubot/manubot/issues/338#issuecomment-1183912661_**
This change is only configurable on source code in the global variable defined on isbn search file.

#337 Set default timeout on ISBN search.

---

manubot/cite/isbn.py
manubot/cite/tests/test_isbn.py

Closes #344
Note that this does not address the other possible issue with Citoid I mentioned here https://github.com/manubot/manubot/issues/344#issuecomment-1264676759
> when there are multiple authors, only the first is listed as an author. The rest are contributors.
I think that problem is with the upstream data, not Manubot.

Swap first and last name in Citoid ISBN metadata

---

manubot/process/header-includes-template.html
manubot/process/tests/manuscripts/example/content/metadata.yaml
manubot/process/util.py

helpful for https://github.com/manubot/rootstock/issues/283
Previously there was only a single date written to `variables.json` (the output manuscript metadata) and that was based on the generated timestamp of the manuscript.
Here we add support for a field in `metadata.yaml` named `date` to set an explicit publication date. The generated timestamp is still retained in the metadata and used to set some additional modified tags in the HTML header. This could be useful when you want to keep a fixed publication date on a manuscript but want to rebuild it to say fix a formatting issue or add new Manubot features.

manuscript metadata: explicit date

---

README.md
manubot/cite/pubmed.py
manubot/pandoc/tests/test_cite_filter/output.txt

closes https://github.com/manubot/manubot/issues/354
`rettype=full` is no longer supported.

get_pubmed_csl_item: use rettype=xml

---

.pre-commit-config.yaml
conftest.py
manubot/cite/arxiv.py
manubot/cite/citations.py
manubot/cite/cite_command.py
manubot/cite/citekey.py
manubot/cite/csl_item.py
manubot/cite/curie/__init__.py
manubot/cite/isbn.py
manubot/cite/pubmed.py
manubot/cite/tests/test_cite_command.py
manubot/cite/tests/test_citekey.py
manubot/cite/tests/test_citekey_api.py
manubot/cite/tests/test_curie.py
manubot/cite/tests/test_doi.py
manubot/pandoc/cite_filter.py
manubot/pandoc/util.py
manubot/process/bibliography.py
manubot/process/manuscript.py
manubot/process/metadata.py
manubot/process/tests/manuscripts/citation-rendering/content/generate-csl-json-combinations.py
manubot/process/tests/test_metadata.py
manubot/process/util.py
manubot/webpage/webpage_command.py
pyproject.toml
setup.cfg

[Ruff](https://github.com/charliermarsh/ruff#pycodestyle-e-w) is an "extremely fast Python linter, written in Rust". It replaces several of our existing tools including flake8, pyupgrade, and isort. It uses the same error codes when possible. Has been gaining popularity recently with rave reviews, so giving it a try.

Replace pre-commit checks with ruff

---

manubot/ai_revision/ai_revision_command.py

Show a proper message if dependencies for the `ai-revision` subcommand were not installed.
I'm not sure what's the best type of exception to thrown within `except`. I'm using `ModuleNotFoundError` now, which shows this message:
```bash
$ manubot ai-revision --content-directory ../rootstock/content/
Traceback (most recent call last):
File "/home/miltondp/projects/others/manubot/manubot/manubot/ai_revision/ai_revision_command.py", line 9, in cli_process
from manubot_ai_editor import models
ModuleNotFoundError: No module named 'manubot_ai_editor'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/miltondp/software/miniconda3/envs/manubot-dev/bin/manubot", line 8, in <module>
sys.exit(main())
^^^^^^
File …
```

ai-revision: show a proper error when dependencies were not installed

---

manubot/pandoc/tests/test_cite_filter/output.txt

manubot/pandoc/tests/test_cite_filter.py::test_cite_pandoc_filter fails on main.
The website [1] states in it's metadata that the article dates from 2016-11-02.
<meta name="citation_publication_date" content="2016/11/02"/>
Most likely, because that is the time for the first submission [2].
Having the test fails because it does not gives the date stated on the website does not good, as the tool is working as intended.
If someone cares about this date, either make a custom local citation or ask the admins of the website to update the metadata for the article.
[1]: https://openreview.net/forum?id=HkwoSDPgg
[2]: https://openreview.net/revisions?id=HkwoSDPgg

FIX: Test fails for no reason.

---

manubot/ai_revision/ai_revision_command.py

Currently, the implementation of `ai_revision_command.py` checks explicitly that a model is of type `GPT3CompletionModel` before providing the `title` and `keywords` arguments read from the manuscript's manifest. This excludes models that derive from `GPT3CompletionModel`, such as the [DebuggingManuscriptRevisionModel](https://github.com/falquaddoomi/manubot-ai-editor/blob/issue-31-customprompts-yaml/libs/manubot_ai_editor/models.py#L578).
This PR uses `issubclassof()` to change the explicit comparison against `GPT3CompletionModel` to comparing whether the model descends from `GPT3CompletionModel` (which `GPT3CompletionModel` itself satisfies).

Fixes AI revision title, keyword propagation for models inheriting from GPT3CompletionModel

---

README.md
manubot/ai_revision/ai_revision_command.py
manubot/command.py
setup.cfg

This PR adds an optional `--config-directory` argument to the `manubot ai-revision` CLI command. If specified, the directory will be searched for the optional files `ai-revision-config.yaml` and `ai-revision-prompts.yaml`, both of which are used to customize the AI revision system.
This PR relies on changes introduced in the not-yet-published `0.5.0` release of `manubot-ai-editor`, hence the version bump in `setup.cfg`. Reviewers should wait until that version is available before approving.

ai-revision command: adds --config-directory argument
