manubot/manubot

manubot/manubot.py, manubot/manuscript.py
Refs https://github.com/greenelab/manubot/issues/3
=> Log timezone

README.md
This is for running tests locally.
=> README: dev environment documentation

.appveyor.yml, README.md, tests/test_manubot.py
Used the following as references:
- https://github.com/ogrisel/python-appveyor-demo/blob/3e6eb8b2f41d0aeaf2cf69105c0cf5aa608b200f/appveyor.yml
- https://github.com/krlmlr/r-appveyor/issues/82
- https://github.com/Tomnl/appveyor-py-test/blob/d17e632c16f7ba571349e2e589e8ac9d031d9596/appveyor.yml
Refs https://github.com/greenelab/manubot/issues/34#issuecomment-392815141
=> Configure AppVeyor for Windows CI testing

manubot/cite/doi.py, manubot/cite/pubmed.py, tests/test_citations.py
Closes https://github.com/greenelab/manubot/issues/45
~~Rebase on #42 when merged.~~ (done)
=> Fetch PMIDs / PMCIDs for DOI references

README.md, tests/test_citations.py, tests/test_command.py, tests/test_readme.py
~~Rebase on #49 once merged.~~ This PR is now independent of #49.
=> Test fidelity of README codeblocks with command ouput

.appveyor.yml, .travis.yml, MANIFEST.in, README.md, manubot/cite/__init__.py, manubot/cite/plain-pandoc-filter.lua, setup.py, tests/test_citations.py, tests/test_readme.py
Work in progress. ~~Rebase on #49 once that is merged.~~
Closes #48
=> manubot cite: option to render references

manubot/cite/pubmed.py, tests/test_citations.py
=> Allow integer months in PMID citations

.gitignore
Adopt sytem specific files from https://github.com/greenelab/manubot-rootstock/commit/135f45193f2bd1f6ce2aa95e06973d19073286d5
With the addition of `.vscode`
=> Add system specific files to .gitignore

manubot/cite/tests/test_isbn.py, manubot/cite/tests/test_url.py, manubot/cite/tests/test_zotero.py, manubot/cite/zotero.py
Refs https://github.com/zotero/translation-server/issues/65
=> translation-server web query: force single result

manubot/process/util.py
read_table deprecated as of pandas v0.24
=> Switch pandas.read_table to read_csv

.travis.yml, README.md, manubot/cite/pubmed.py, manubot/cite/tests/test_util.py, manubot/cite/zotero.py, manubot/process/tests/manuscripts/example/content/citation-tags.tsv, manubot/process/tests/test_manuscript.py, release-notes/v0.2.0.md, release-notes/v0.2.1.md, release-notes/v0.2.2.md, setup.py
Closes https://github.com/manubot/manubot/issues/94
=> Relocate repo from greenelab/manubot to manubot/manubot

manubot/cite/doi.py, manubot/cite/tests/test_doi.py, manubot/cite/tests/test_util.py, manubot/cite/util.py, manubot/process/tests/manuscripts/example/content/02.body.md
=> Support shortDOI citation

README.md
Not sure if we want to leave a link to the version of the article produced by manubot.
=> Update citation to PLOS CB

README.md
Now rebased on https://github.com/manubot/manubot/pull/119
=> Update README with software paper & clarify scope

README.md
Added installation via PyPI. Installation should be explained before usage.
=> Extend documentation of installation

README.md, manubot/process/ci.py, manubot/process/tests/test_ci.py, manubot/process/util.py
Closes https://github.com/manubot/manubot/issues/130
=> Generalize CI variables, support AppVeyor

manubot/cite/cite_command.py, manubot/cite/tests/test_cite_command.py, manubot/pandoc/bibliography.py, manubot/tests/test_util.py, manubot/util.py, manubot/webpage/webpage_command.py
Refs https://github.com/manubot/rootstock/pull/265#issuecomment-528602414
=> Fix webpage warning during ots upgrade

manubot/process/tests/test_ci.py
closes https://github.com/manubot/manubot/issues/140
supercedes https://github.com/manubot/manubot/pull/148
=> skip test_get_continuous_integration_parameters_* on forks

manubot/webpage/webpage_command.py
Maybe will fix the problem in https://github.com/manubot/manubot/issues/165 ?
=> Define `process` before referencing it

README.md, manubot/process/tests/manuscripts/example/content/01.front-matter.md, manubot/process/thumbnail.py, manubot/process/util.py
closes https://github.com/manubot/manubot/issues/172
will require rootstock changes to frontmatter
=> Combine pandoc metadata and jinja2 variables into a single dictionary

manubot/process/util.py
refs https://github.com/manubot/manubot/issues/177#issuecomment-557551687
=> Log user-provided variables at debug level

manubot/process/metadata.py, manubot/process/util.py
refs https://github.com/manubot/rootstock/issues/282
=> process: add software versions to variables

manubot/cite/zotero.py
Convenient function for third-party users
Indented as an API with similar functionality to the search box of zoterobib:
- https://zbib.org/
- https://github.com/zotero/bib
- https://github.com/zotero/bib-web
=> zotero search_or_web_query to support URL or ID lookup

manubot/cite/arxiv.py, manubot/cite/csl_item.py, manubot/cite/tests/test_csl_item.py
~~work in progress. need to test and decide whether this is too complex / whether we should rely on a third party package like dateutil~~
=> CSL_Item: add date IO functionality

manubot/process/util.py
=> Follow up tweaks to pandoc-manubot-cite

.github/workflows/test.yml, manubot/webpage/tests/test_webpage_command.py
https://github.com/r-lib/actions/tree/master/setup-pandoc
https://twitter.com/maxheld/status/1218242371428798465
Thanks @jimhester for creating this action! Really makes using pandoc as part of the workflow much more straightforward!
=> Use r-lib/actions/setup-pandoc for pandoc install

manubot/cite/curie/__init__.py, manubot/cite/curie/namespaces.json, manubot/cite/tests/test_curie.py, manubot/cite/tests/test_unpaywall.py, setup.py
refs https://github.com/manubot/manubot/issues/218
refs https://github.com/manubot/manubot/issues/220
=> cite.curie module for compact identifiers via identifiers.org

manubot/cite/curie/__init__.py, manubot/cite/tests/test_citekey.py
closes https://github.com/manubot/manubot/issues/236
=> Fix Handler_CURIE.inspect when namespaceEmbeddedInLui=true

manubot/cite/citations.py, manubot/cite/cite_command.py, manubot/cite/tests/test_cite_command.py, manubot/cite/tests/test_unpaywall.py
closes https://github.com/manubot/manubot/issues/240
=> cite command: preserve order of input citekeys in output

conftest.py, manubot/cite/citations.py, manubot/cite/cite_command.py, manubot/cite/tests/test_cite_command.py, manubot/cite/tests/test_citekey.py, manubot/pandoc/cite_filter.py, manubot/pandoc/tests/test_cite_filter/output.txt, manubot/process/util.py, manubot/tests/test_command.py
Update authors in Papernot et al. reference
=> Fix failing cite filter and black tests

manubot/cite/tests/test_url.py, manubot/cite/url.py, manubot/cite/zotero.py
closes https://github.com/manubot/manubot/issues/244
=> get_url_csl_item_zotero: set missing URL

.appveyor.yml, .github/workflows/test.yml, .travis.yml, manubot/cite/pubmed.py, setup.py
refs https://github.com/manubot/manubot/issues/248
=> Support and test on Python 3.9

manubot/cite/pubmed.py
refs https://github.com/manubot/manubot/issues/257
=> ignore ratelimiter DeprecationWarning

README.md, manubot/process/metadata.py, manubot/process/tests/manuscripts/citation-rendering/readme.md
precursor to https://github.com/manubot/rootstock/pull/399
=> update rootstock default branch to main

manubot/pandoc/util.py
This pull request should solve issue #286
=> Checking pandoc-citeproc version only if it is required (i.e. for older pandoc versions)

.pre-commit-config.yaml, manubot/cite/citations.py, manubot/cite/doi.py, manubot/cite/tests/test_cite_command.py, manubot/pandoc/bibliography.py, manubot/pandoc/tests/test_cite_filter.py, manubot/process/metadata.py, manubot/process/tests/test_process_command.py, manubot/tests/test_command.py, manubot/webpage/tests/test_webpage_command.py
Automatically keeps our python code up to date for the lowest version we want to support (currently 3.7).
See https://github.com/asottile/pyupgrade
=> pre-commit: run pyupgrade --py37-plus

manubot/cite/pubmed.py, setup.cfg
throttler required using async which was too complicated Use pyrate_limiter instead.
https://github.com/vutran1710/PyrateLimiter
=> use pyrate_limiter for rate limited requests

.appveyor.yml, .github/workflows/test.yml, .pre-commit-config.yaml, README.md
follows https://github.com/manubot/manubot/pull/346
=> Test on Python 3.11

.appveyor.yml
refs https://github.com/manubot/manubot/pull/348#issuecomment-1325218641
=> appveyor: reduce pytest to appveyor marked only

manubot/cite/citeproc.py
refs https://github.com/manubot/manubot/issues/352
=> CSL schema: upgrade to v1.0.2

.github/workflows/test.yml, manubot/cite/citeproc.py, manubot/cite/curie/__init__.py, manubot/cite/pubmed.py, manubot/pandoc/util.py, manubot/process/metadata.py, pyproject.toml, setup.cfg
closes https://github.com/manubot/manubot/issues/367
=> drop py37, require pyrate-limiter <3
